---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: debian-7.8
  - name: debian-8.2

suites:
  - name: default
    run_list:
      - recipe[t3-base::default]
    attributes:
  - name: physical
    run_list:
      - recipe[t3-base::default]
      - recipe[t3-base::_physical]
  - name: production
    run_list:
    - recipe[t3-base::default]
    attributes:
      t3-base:
        flags:
          production: true
      virtualization:
        host: test.vagrant
      t3-base:
        prevent-t3-chef-client-inclusion-for-testing: true