---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.8
  - name: debian-8.2

suites:
  - name: default
    run_list:
      - recipe[t3-base::default]
    attributes:
  - name: physical
    run_list:
      - recipe[t3-base::default]
      - recipe[t3-base::_physical]